#!/bin/bash



# no bootservers and fatclients & no empty puavobox
case "$(puavo-conf puavo.hosttype)" in
    bootserver|fatclient)
	sleep 9999999999999999999
	;;
    *)
	puavobox=$(puavo-conf puavo.puavobox 2>/dev/null)
	case "$puavobox" in
	    "")
		sleep 9999999999999999999
		;;
	    *)
		;;
	esac	
	;;
esac


# here we go
old=""
dns=false
while true; do
    if nm-online -q -t 3600; then
 	 if host cups "$puavobox" >/dev/null  2>&1 ; then
	     if ! $dns; then
	         echo "nameserver $puavobox" > /etc/resolv.conf
		 dns=true
	     fi	     
	     # is the route here?
	     if ip route | grep -q "10.249.0.0/20";then
		 # that's fine
		 true
	     else
		 # add route ans set dns 
		 old=$(ip route|grep default)
		 ip route add 10.249.0.0/20 via "$puavobox"
	     fi
	     sleep 60
	     # did the default route change?
	     new=$(ip route|grep default)
	     if test "$old" != "$new"; then
		 # remove route
		 ip route | grep -q 10.249.0.0/20 && ip route del 10.249.0.0/20
	     fi
	 else
	     if $dns; then
	         echo "nameserver 127.0.0.1" > /etc/resolv.conf
		 dns=false
	     fi	     
	 fi    
    fi
done

# never reaches here
exit 
